# Generated by Django 4.2 on 2023-05-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Car model')),
                ('img', models.ImageField(upload_to='car_images', verbose_name='Car image')),
                ('price', models.PositiveBigIntegerField(verbose_name='Car price')),
            ],
        ),
    ]
